Infrastructure Integration Test for Scaffold (#167)

diff --git a/smoke-test-pipeline.yml b/smoke-test-pipeline.yml
--- a/smoke-test-pipeline.yml
+++ b/smoke-test-pipeline.yml
@@ -3,12 +3,12 @@ trigger: none
 schedules:
 - cron: "0 3 * * *"
   branches:
-    include: [ master ] 
+    include: [ master ]
   displayName: M-F 7:00PM (UTC - 8:00) Pacific daily build
   always: true
 
 variables:
-- group: 'spk-vg'  
+- group: 'spk-vg'
 
 stages:
 - stage: integration_tests
@@ -41,24 +41,28 @@ stages:
         echo "TEST_SCRIPT: $TEST_SCRIPT"
         curl $TEST_SCRIPT >| validations.sh
         chmod +x ./validations.sh
+        echo "TEST_SCRIPT2: $TEST_SCRIPT2"
+        curl $TEST_SCRIPT2 >| infra-validations.sh
+        chmod +x ./infra-validations.sh
       displayName: "Download integration test scripts"
       env:
         FUNC_SCRIPT: $(FUNC_SCRIPT)
         TEST_SCRIPT: $(TEST_SCRIPT)
-    - bash: | 
+        TEST_SCRIPT2: $(TEST_SCRIPT2)
+    - bash: |
         # Install the extension
         export AZURE_DEVOPS_EXT_PAT=$(AZDO_PAT)
         az extension add --name azure-devops
-        
-        # Login to Azure 
+
+        # Login to Azure
         echo "az login --service-principal --username $(SP_APP_ID) --password $(SP_PASS) --tenant $(SP_TENANT)"
         az login --service-principal --username "$(SP_APP_ID)" --password "$(SP_PASS)" --tenant "$(SP_TENANT)"
-        
+
         # Step up git identity
         git config --global user.email "me@microsoft.com"
         git config --global user.name "Service Account"
 
-        #Set ENV VARs
+        # Set ENV VARs
         export SPK_LOCATION="$(pwd)/spk-linux"
         export ACCESS_TOKEN_SECRET=$(AZDO_PAT)
         export SP_PASS=$(SP_PASS)
@@ -73,8 +77,15 @@ stages:
         # Get exit status
         status=$?
         [ $status -eq 0 ] && echo "Test Done!" || (echo "Test had issues" && exit 1)
+
+        # Run the infra test
+        bash ./infra-validations.sh
+
+        # Get exit status
+        status=$?
+        [ $status -eq 0 ] && echo "Infra Test Done!" || (echo "Infra Test had issues" && exit 1)
       #failOnStderr: true
-      displayName: "Run Tests"
+      displayName: "Run Validation Tests"
     - task: PublishPipelineArtifact@1
       inputs:
         path: $(System.DefaultWorkingDirectory)/spk-env/log.txt
